#Make a python specific dockerfile

FROM ubuntu

RUN apt-get update && apt-get upgrade -y && apt-get install -y python3.7 vim git

CMD bash

#build with: docker build -t [name] .
#run with:   docker run -it [same name] 
